### PR TITLE
Add awesomium step for linux hosts

### PR DESCRIPTION
**Pull request by evan-a-a**
Only windows was requiring the Awesomium library, but it is needed for linux as well.

Signed-off-by: Evan Anderson evan1124@gmail.com

### CODE REVIEW

**Comment by wrongu** [comment]
FindAwesomium and the CMakeLists was updated in the glfw branch - but yes I forgot to add it to the readme. Can you update this to work from those changes, or at least make sure they merge easily?

**Comment by evan-a-a** [comment]
Ahh didn't see that.  Merged the changes.

**Comment by adam4813** [comment]
Either put this inside the GLFW branch as most of the linux fixes are in there, or wait until the GLFW branch gets merged into develop (should be soon if someone can just validate the Mac build).

**Comment by adam4813** [comment]
Ok the cmake file makes reference to SDL2 which is gone now. Please update the file and I will accept the PR.

**Comment by adam4813** [comment]
Scratch my last comment. It would seem these changes except for the read me have already been implemented.

**Pull request closed without merging**
