### PR TITLE
Formatting, Refactoring, etc

### PR DESCRIPTION
**Pull request by wrongu**
Working out of my "formatting" branch, I have been trying to get everything to look consistent and behave nicely. I've been looking for things like
- const wherever possible
- lots and lots of comments
- includes all in once place
- both pragma once and ifdef/define/endif
- consistent curly-brace use

On top of this, I did a lot of refactoring of GLMesh, GLIcoSphere, and GLCubeSphere. Notable changes include
- GLIcoSphere and GLCubeSphere now extend GLMesh and use its drawing methods
- A GLMesh can have any shader. A static map is used to avoid duplicate programs in memory.
- the Refine() methods of GLCubeSphere and GLIcoSphere are hugely refactored and documented so that they make sense now!
- All 3 of these classes are now in the Sigma:: namespace
- Other classes like IGLComponent, OpenGLSystem, etc are also updated to reflect these changes

### CODE REVIEW

**Comment by adam4813** [comment]
Give some thoughts to those comments and let me know what you think.

**Comment by wrongu** [comment]
Absolutely.
In the small projects I've done before, include trails were never a problem. But it makes total sense.
I'll change Vector3f to glm::vec3, but I do think that a distinction should be made between points and vectors.

**Comment by adam4813** [comment]
2 different things, points and vectors. I'm guessing you mean verticies.
Vectors are either a) a origin and direction, or b) a set of numbers or in
c++ a set of similar items.

Verticies are just a location and other related data for that location or
point.

**Comment by wrongu** [comment]
C++'s `<vector>` is muddying this a bit.. I am referring to (a), the mathematical definition of "vector".

Yes - mesh vertices are _points_ (with other data) in the mathematical sense. Something like a vertex normal, however, is a locationless (..."pointless"?) direction. In some ways, this is a silly distinction to make. It is only useful insofar as well-designed code architecture should respect the mathematical concepts it is modeling.. Which I've always done as much as possible.

**Pull request merged**
