### PR TITLE
Linux + glfw (ubuntu 13.04)

### PR DESCRIPTION
**Pull request by wrongu**
this time with 40% less junk code!

cmake:
- added FindAwesomium
- fixed "awsomeium" typos
- findGLFW3 looks for libglfw3
- extra `-l` switches added for X11/glfw compatibility

source:
- include wglew.h is blocked on *nix
- glewExperiemental set to TRUE (fixes some context problems with using X11?) (should this be guarded as *nix-only?)

### CODE REVIEW

**Comment by aponigricon** [comment]
> 40%

Is that an actual number, or just something you're pulling out of your arse? :laughing:

**Comment by wrongu** [comment]
Arse.
Actually looking at the numbers, I have more changes in this PR than in my last one (88+, 23- vs 85+, 26-). The difference is that there are no changes here irrelevant to the task of Linux compilation.

**Comment by ghost** [comment]
It still puts 4 spaces in the middle of tabs (CMakeLists.txt)

Also, for some reason I don't need any of those `-l` flags when using GLFW 3.0.3 built with `-DBUILD_SHARED_LIBS=ON`.

**Comment by wrongu** [comment]
I tried BUILD_SHARED_LIBS once. I'll uninstall and try again.
_edit_ it worked this time!

**Pull request merged**
