### PR TITLE
Simple Fix to Detect Depth Buffer Bit Depth

### PR DESCRIPTION
**Pull request by tanderegg**
This method should determine which bit depth to use for the GBuffer's FBO.  Please test.

### CODE REVIEW

**Comment by aponigricon** [comment]
But that means that if we're going to use logarithmic z-buffers, then each buffer would be restricted by the restrictions of a 16-bit one... unless we can take different bit widths into account?

**Comment by adam4813** [comment]
Doesn't work on my end unless I change some glfwwindowhints.

Also the 32 bit works on my system, but the unlit items are failing the depth testing.

**Comment by tanderegg** [comment]
What glfwwindowhints do you need to use?

**Comment by tanderegg** [comment]
I changed this PR to use a different approach, basically it doesn't create the actual frame buffer object until after the color buffers and depth buffer have been created.  Please test.

**Comment by Zardoz89** [comment]
Looks that works for me. It shows that the depth buffer size is of 24 bits.

Tested on : 
Kubuntu GNU/Linux 13.04 x64
Geforce GTX 660 -> NVIDIA proprietary driver 319

**Pull request merged**
