### PR TITLE
Harmonize the type of entity id and creates a general inclusion file.

### PR DESCRIPTION
**Pull request by catageek**
Entity id's types have been seen as:
- size_t
- int
- unsigned int

This PR creates a id_t type that is used everywhere.

### CODE REVIEW

**Comment by Zardoz89** [comment]
I saw that id_t is a unsigned int. Not should be a type that always we know what size have. Think that size of unsigned int could be different between 32 and 64 bit machines and could depend of compiler being used.

You can see how define a fixed integer size in a portable way here : https://github.com/Zardoz89/RC3200-VM/blob/master/include/Types.hpp

**Comment by catageek** [comment]
You're right.

**Comment by adam4813** [comment]
Do note that I doubt you will ever need that many entities (read an entity
id above the 32bit mark).

**Comment by catageek** [comment]
It is not a problem because we need a compiler supporting C++11 to compile Sigma. Starting with VC11, MS has a decent C++11 support, not before, So there is non need to manage older compilers..

**Comment by Zardoz89** [comment]
You are right. :+1:

**Comment by adam4813** [comment]
Is this PR dead with your latest?

**Comment by catageek** [comment]
It is included in the big ECS PR, but without the last commit. For this reason, it is not dead.

**Pull request merged**
