### PR TITLE
Add BitArray template class

### PR DESCRIPTION
**Pull request by catageek**
Add BitArray template class that aims to provide some of the functionality of boost::dynamic_bitset.

Iterators must be implemented to find the first index at true or false. the "count leading zero's" builtin functions of compilers can improve the performance.

Be careful that values are stored from LSB to MSB when index increases.

### CODE REVIEW

**Comment by catageek** [comment]
An example for using it to store a unique ID:

// instantiate the array with default value at "1". We get a shared pointer
auto freeID_ptr = BitArray<unsigned long long>::Create(true); // we use 8-byte-blocks to store the data
auto freeID = *freeID_ptr;

An id is free if the bit is set to 1, or true.

The function to find the first free ID must be written. We must find the first block that is not 0 and find the index of the first bit set starting from the LSB. The ID will be (block_index \* blocksize) + bit_index.

reserve an ID
UIDarray[id] = false; // set the bit to 0

release an ID
UIDarray[id] = true;

**Comment by adam4813** [comment]
Ah I thought that was the use, but just wanted to make sure. This will come in handy for sure and be a very compact method to store the free ID set.

Before we merge this over can you implement the method to find the first free ID?

**Comment by catageek** [comment]
I will do this tonight.

**Comment by catageek** [comment]
Eventually I made the UniqueIDProvider class.

**Comment by catageek** [comment]
Not synched with current ECS PR, closing

**Pull request closed without merging**
