### PR TITLE
Add Logger and Logger API into Sigma

### PR DESCRIPTION
**Pull request by jlitewski**
This pull request adds a Logger to Sigma, and also fixes some bugs.

### CODE REVIEW

**Comment by kmclarnon** [comment]
This is in essence a singleton implementation and as such, suffers from two major issues as far as game engines are concerned.
1.  You provide global access through a static get, which initializes the logger if it hasn't been already.  This can easily be done without a shared pointer since this system will exist throughout the lifetime of the program (since its a global) and there isn't really any reason for it to be destroyed before the program is shutdown, as its the logger.  Using a shared pointer adds needless reference counting into the mix.
2. This system utilizes lazy initialization, which is usually a bad idea, as it can make debugging much more difficult, and more importantly it isn't needed, so it is just an unnecessary optimization.

Just make it a regular class, like any other, and have it created explicitly inside a std::unique_ptr by the initialization routines and pass around constant pointers or references to it.  Not only will that make it easier to debug any problems, but it will be required anyways if you want to have multiple loggers, which you very well could, for multiple files/threads etc.

**Comment by jlitewski** [comment]
is very true, I was just following how FactorySystem worked, since I'm still fairly new to how C++ works. I'll remove the Singleton stuff. Also, do you have any resources for how to do the std::unique_ptr<> stuff?

**Comment by wrongu** [comment]
This is a good source: http://en.cppreference.com/w/cpp/memory

**Comment by jlitewski** [comment]
Okay, hopefully this is better. Couldn't figure out how to use the std::unique_ptr<>, but the Sigma::Logger is now a normal, non-Singleton class.

**Comment by kmclarnon** [comment]
Unique pointer is pretty straightforward to use:

```
class SomeClass() { ... };

void somePFunc(const SomeClass* p) { ... }
void someRFunc(const SomeClass& p) { ... }

int main()
{
    {
        std::unique_ptr<SomeClass> u = std::unique_ptr<SomeClass>(new SomeClass(...));
        somePFunc(u.get());
        someRFunc(*u);
    }  // leaving scope, u, and the SomeClass it contains will be destroyed
}
```

There are some cases where it gets a little bit more messy, usually when you have to use custom deleters, but it's really not that bad.

**Comment by jlitewski** [comment]
alright, I'll tinker with it after work tonight then.

**Comment by jlitewski** [comment]
Closing this to redo it later, after figuring out more C++ stuff.

**Pull request closed without merging**
