### PR TITLE
Add optional parameters to control the OpenGL Texture

### PR DESCRIPTION
**Pull request by Zardoz89**
Also fix the swaped Red and Blue channels being swaped, plus add some documentation

### CODE REVIEW

**Comment by Zardoz89** [comment]
I'm thinking un doing some changes like storing the parameters un GLtexture and adding two methods to allow edit the parameters.

**Comment by adam4813** [comment]
The member initialization of C++11 in the class declaration isn't supported in Visual Studio yet.

Please move them to the constructor for the time being.

Also please prefer tabs for indentation for consistency.

**Comment by Zardoz89** [comment]
Ok! I should do it today when I return from the work. Also I need to set Vim for the indentation with tabs.

**Comment by adam4813** [comment]
Also now basic shaders aren't needed.

**Comment by adam4813** [comment]
Ok I did merge this but for some reason it doesn't recognize it.

**Pull request closed without merging**
