### PR TITLE
Fix the build and the instructions for Sigma+CEF on OS X.

### PR DESCRIPTION
**Pull request by DeVaukz**

### CODE REVIEW

**Comment by DeVaukz** [comment]
No idea why the travis build fails.

**Comment by adam4813** [comment]
Sorry the last PR broke your's most likely because of a merge conflict in README.

Can you update this, as I don't know the exact the exact end result you needed.

**Comment by DeVaukz** [comment]
Merged.

**Comment by DeVaukz** [comment]
Merged with the MS 2.5 changes.

**Pull request merged**
